### ISSUE TITLE
Error if config.cson is open

### ISSUE THREAD

**Issue by tagyoureit** [willyelm/atom-bugs#16]
I was trying to find out how to pass command line arguments to the app (found it by clicking "Current File"), but in the process I had opened the config.cson file.  The following error was thrown:

```
/Users/myname/.atom/config.cson:1
(function (exports, require, module, __filename, __dirname) { "*":
                                                                 ^
SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.runMain [as _onTimeout] (module.js:441:10)
    at Timer.listOnTimeout (timers.js:92:15)
```

Once I closed the config.cson file, everything worked as expected.

**Comment by willyelm** [comment]
please try with the latest version, thanks!
