### ISSUE TITLE
Error: listen EADDRINUSE :::5858

### ISSUE THREAD

**Issue by QuentinDela** [willyelm/atom-bugs#8]
After triggering nightmarejs

```
Error: listen EADDRINUSE :::5858
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at Agent.Server._listen2 (net.js:1246:14)
    at listen (net.js:1282:10)
    at Agent.Server.listen (net.js:1378:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:85:44)
    at node.js:444:3
```

**Comment by QuentinDela** [comment]
To kill the process
https://github.com/nodejs/node/issues/3469#issuecomment-245292028

**Comment by willyelm** [comment]
Please try with the latest version which has been moved here: https://github.com/atom-bugs/atom-bugs
